//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string EATFOOD = "eatfood";
        
        public const string HEARTBEAT = "heartbeat";
        
        public const string GAME_START = "game_start";
        
        public const string SLASHBACK2_BODY = "slashback2_body";
        
        public const string GRABOBJECT_RIGHT = "grabobject_right";
        
        public const string PUTWAISTSLOT_RIGHT = "putwaistslot_right";
        
        public const string PUTWAISTSLOT_CENTER = "putwaistslot_center";
        
        public const string RIDINGVEHICLE = "ridingvehicle";
        
        public const string PUTWAISTSLOT_LEFT = "putwaistslot_left";
        
        public const string TAKEBACKSLOT_LEFT = "takebackslot_left";
        
        public const string GRABOBJECT_LEFT = "grabobject_left";
        
        public const string RECOILNORMAL_LEFT = "recoilnormal_left";
        
        public const string RECOILSTRONG_RIGHT = "recoilstrong_right";
        
        public const string PUTBACKSLOT_RIGHT = "putbackslot_right";
        
        public const string RECOILWEAK_RIGHT = "recoilweak_right";
        
        public const string TAKEWAISTSLOT_LEFT = "takewaistslot_left";
        
        public const string RECOILSTRONG_LEFT = "recoilstrong_left";
        
        public const string SHOTGUN = "shotgun";
        
        public const string RECOILWEAK_LEFT = "recoilweak_left";
        
        public const string BLOCKSHIELD_RIGHT = "blockshield_right";
        
        public const string HEARTBEAT_FAST = "heartbeat_fast";
        
        public const string TAKEWAISTSLOT_CENTER = "takewaistslot_center";
        
        public const string SLASHFRONT2_BODY = "slashfront2_body";
        
        public const string TAKEBACKSLOT_RIGHT = "takebackslot_right";
        
        public const string PUTBACKSLOT_LEFT = "putbackslot_left";
        
        public const string SLASHFRONT1_BODY = "slashfront1_body";
        
        public const string GUUUUN = "guuuun";
        
        public const string KNIFE = "knife";
        
        public const string IN_THE_RAIN = "in_the_rain";
        
        public const string BOOOMB = "booomb";
        
        public const string IMPACTWEAK_HEAD = "impactweak_head";
        
        public const string IMPACTSTRONG_HEAD = "impactstrong_head";
        
        public const string IMPACTSTRONG_BODY = "impactstrong_body";
        
        public const string DRINKPOTION = "drinkpotion";
        
        public const string SLASHBACK1_BODY = "slashback1_body";
        
        public const string RECOILNORMAL_RIGHT = "recoilnormal_right";
        
        public const string TAKEWAISTSLOT_RIGHT = "takewaistslot_right";
        
        public const string IN_THE_HEAVYRAIN = "in_the_heavyrain";
        
        public const string BLOCKSHIELD_LEFT = "blockshield_left";
        
        public const string IMPACTWEAK_BODY = "impactweak_body";
    }
}
